[tool.black]
line_length = 88
skip-string-normalization = true
target-version = ['py311','py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific for Django.
  | tests
  | migrations
  | \.venv
  | \.venv3
  | \.git
  | help-man
)/
'''

[tool.djlint]
profile = "django"
ignore = "T002,T003"
indent=2
max_blank_lines=1
max_attribute_length=70 # default: 70
max_line_length=100     # default: 120
close_void_tags=true    # Ex: <img> becomse <img />
# line_break_after_multiline_tag=true
format_attribute_template_tags=true
use_gitignore=true

[tool.isort]
profile = "black"
blocked_extensions = [
    "rst","html","js","svg","txt","css","scss","png","snap","tsx"
]
combine_as_imports = true
default_section = "THIRDPARTY"
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true
known_django = "django"
sections=["FUTURE","STDLIB","DJANGO","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
skip = ["migrations",".git","__pycache__","LC_MESSAGES"]
src_paths = ["src","src/apps","src/compat"]
line_length = 88
multi_line_output = 3
no_lines_before="LOCALFOLDER"
